name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git init .
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_REF}"
          git checkout --detach FETCH_HEAD
      - name: Test
        run: |
          node --version
          npm --version
          npm test
